# mixed_effects_models.R
# Script to run mixed effects models on overclaiming behavior

if (!requireNamespace("lme4", quietly = TRUE)) {
  install.packages("lme4", repos = "http://cran.us.r-project.org")
}
if (!requireNamespace("haven", quietly = TRUE)) {
  install.packages("haven", repos = "http://cran.us.r-project.org")
}

library(haven)
library(lme4)
library(dplyr)

# Load the long-format dataset generated by analysis_time.R
df_long <- read_dta("analysis_time_long.dta")

# Ensure id and genre_id are factors for random effects
df_long$id <- as.factor(df_long$id)
df_long$genre_id <- as.factor(df_long$genre_id)

print("Fitting Mixed Effects Logistic Regression for Overclaiming (Unconditional)...")

# Mixed-effects logistic regression on the FULL dataset:
# Predicting the probability that a person overclaims a genre (like=1, listen=0)
# out of all possible 20 genres.
model_overclaim_uncond <- glmer(
  overclaim ~ educ2 + child_arts + agecat + female + income + as.factor(race5) + 
    (1 | id) + (1 | genre_id), 
  data = df_long, 
  family = binomial,
  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5))
)

summary(model_overclaim_uncond)

# Let's also do a person-level model for the total volume of overclaiming
# We can aggregate back up to the person level
df_person <- df_long %>%
  group_by(id, educ2, child_arts, agecat, female, income, race5) %>%
  summarize(total_overclaim = sum(overclaim, na.rm = TRUE), .groups = 'drop')

print("Fitting Poisson Regression for Total Volume of Overclaiming (Person-level)...")
model_overclaim_count <- glm(
  total_overclaim ~ educ2 + child_arts + agecat + female + income + as.factor(race5),
  data = df_person,
  family = poisson
)

summary(model_overclaim_count)

saveRDS(model_overclaim_uncond, "mixed_model_overclaim_uncond.rds")
saveRDS(model_overclaim_count, "model_overclaim_count.rds")
print("Models saved.")

