# mixed_effects_models.R
# Script to run mixed effects models on overclaiming behavior

if (!requireNamespace("lme4", quietly = TRUE)) {
  install.packages("lme4", repos = "http://cran.us.r-project.org")
}
if (!requireNamespace("haven", quietly = TRUE)) {
  install.packages("haven", repos = "http://cran.us.r-project.org")
}

library(haven)
library(lme4)
library(dplyr)

# Load the long-format dataset generated by analysis_time.R
df_long <- read_dta("analysis_time_long.dta")

# Ensure id and genre_id are factors for random effects
df_long$id <- as.factor(df_long$id)
df_long$genre_id <- as.factor(df_long$genre_id)

# Filter out rows where the person didn't even like the genre 
# (Since "overclaiming" is structurally 0 if they don't claim to like it)
# Or we can model unconditional overclaiming. Let's model conditional overclaiming first.
df_cond <- df_long %>% filter(like == 1)

print("Fitting Mixed Effects Logistic Regression for Overclaiming (Conditional on Liking)...")

# Mixed-effects logistic regression:
# Predicting overclaiming based on demographics, with random intercepts for person (id) and genre (genre_id)
# This asks: "Given that someone said they liked a genre, what predicts them NOT having it in their recent playlist?"
model_overclaim <- glmer(
  overclaim ~ educ2 + agecat + female + income + as.factor(race5) + 
    (1 | id) + (1 | genre_id), 
  data = df_cond, 
  family = binomial,
  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5))
)

summary(model_overclaim)

# Save the model object
saveRDS(model_overclaim, "mixed_model_overclaim.rds")
print("Model saved to mixed_model_overclaim.rds")
