<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Musical Overclaiming: Liking vs.&nbsp;Listening in the Abstract</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="overclaiming_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="overclaiming_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="overclaiming_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="overclaiming_report_files/libs/quarto-html/popper.min.js"></script>
<script src="overclaiming_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="overclaiming_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="overclaiming_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="overclaiming_report_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="overclaiming_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="overclaiming_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="overclaiming_report_files/libs/bootstrap/bootstrap-62e2d20df198e8a01bb734742f2e28cf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-wrangling-variables-and-preparation" id="toc-data-wrangling-variables-and-preparation" class="nav-link" data-scroll-target="#data-wrangling-variables-and-preparation">Data Wrangling, Variables, and Preparation</a>
  <ul class="collapse">
  <li><a href="#abstract-genre-liking" id="toc-abstract-genre-liking" class="nav-link" data-scroll-target="#abstract-genre-liking">Abstract Genre Liking</a></li>
  <li><a href="#concrete-listening-behavior" id="toc-concrete-listening-behavior" class="nav-link" data-scroll-target="#concrete-listening-behavior">Concrete Listening Behavior</a></li>
  <li><a href="#complex-taste-indicators" id="toc-complex-taste-indicators" class="nav-link" data-scroll-target="#complex-taste-indicators">Complex Taste Indicators</a></li>
  <li><a href="#cultural-capital-indicators" id="toc-cultural-capital-indicators" class="nav-link" data-scroll-target="#cultural-capital-indicators">Cultural Capital Indicators</a></li>
  <li><a href="#other-socio-demographic-variables" id="toc-other-socio-demographic-variables" class="nav-link" data-scroll-target="#other-socio-demographic-variables">Other Socio-Demographic Variables</a></li>
  <li><a href="#statistical-modeling-strategy" id="toc-statistical-modeling-strategy" class="nav-link" data-scroll-target="#statistical-modeling-strategy">Statistical Modeling Strategy</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#step-1-genre-level-complex-tastes-random-intercept-estimates" id="toc-step-1-genre-level-complex-tastes-random-intercept-estimates" class="nav-link" data-scroll-target="#step-1-genre-level-complex-tastes-random-intercept-estimates">Step 1: Genre-Level Complex Tastes: Random Intercept Estimates</a></li>
  <li><a href="#step-2-global-variable-importance-bayesian-joint-wald-tests" id="toc-step-2-global-variable-importance-bayesian-joint-wald-tests" class="nav-link" data-scroll-target="#step-2-global-variable-importance-bayesian-joint-wald-tests">Step 2: Global Variable Importance: Bayesian Joint Wald Tests</a>
  <ul class="collapse">
  <li><a href="#best-predictor-analysis" id="toc-best-predictor-analysis" class="nav-link" data-scroll-target="#best-predictor-analysis">Best Predictor Analysis</a></li>
  <li><a href="#detailed-coefficient-estimates-across-complex-tastes" id="toc-detailed-coefficient-estimates-across-complex-tastes" class="nav-link" data-scroll-target="#detailed-coefficient-estimates-across-complex-tastes">Detailed Coefficient Estimates Across Complex Tastes</a></li>
  <li><a href="#visualizing-the-effect-of-arts-exposure-on-complex-tastes" id="toc-visualizing-the-effect-of-arts-exposure-on-complex-tastes" class="nav-link" data-scroll-target="#visualizing-the-effect-of-arts-exposure-on-complex-tastes">Visualizing the Effect of Arts Exposure on Complex Tastes</a></li>
  <li><a href="#methodological-note-the-divergence-of-omnivorousness-and-cap-constraints" id="toc-methodological-note-the-divergence-of-omnivorousness-and-cap-constraints" class="nav-link" data-scroll-target="#methodological-note-the-divergence-of-omnivorousness-and-cap-constraints">Methodological Note: The Divergence of Omnivorousness and Cap Constraints</a></li>
  </ul></li>
  <li><a href="#step-3-bayesian-model-comparison" id="toc-step-3-bayesian-model-comparison" class="nav-link" data-scroll-target="#step-3-bayesian-model-comparison">Step 3: Bayesian Model Comparison</a></li>
  <li><a href="#step-4-link-between-overclaiming-odds-and-genre-characteristics" id="toc-step-4-link-between-overclaiming-odds-and-genre-characteristics" class="nav-link" data-scroll-target="#step-4-link-between-overclaiming-odds-and-genre-characteristics">Step 4: Link Between Overclaiming Odds and Genre Characteristics</a>
  <ul class="collapse">
  <li><a href="#bayesian-posterior-odds-of-overclaiming" id="toc-bayesian-posterior-odds-of-overclaiming" class="nav-link" data-scroll-target="#bayesian-posterior-odds-of-overclaiming">Bayesian Posterior Odds of Overclaiming</a></li>
  <li><a href="#correlation-between-overclaiming-odds-and-genre-characteristics" id="toc-correlation-between-overclaiming-odds-and-genre-characteristics" class="nav-link" data-scroll-target="#correlation-between-overclaiming-odds-and-genre-characteristics">Correlation Between Overclaiming Odds and Genre Characteristics</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Musical Overclaiming: Liking vs.&nbsp;Listening in the Abstract</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This report was generated using AI under general human direction. At the time of generation, the contents have not been comprehensively reviewed by a human analyst.</p>
</div>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Research on cultural consumption has overwhelmingly studied tastes, and to a lesser extent, knowledge, practices, and meaning-making. While these research agendas have mostly traveled along different—albeit sometimes parallel—tracks, recent theoretical advances have united them into the analysis of what <span class="citation" data-cites="ma2025">Ma (<a href="#ref-ma2025" role="doc-biblioref">2025</a>)</span> calls “complex tastes.” In this framework, valuations (conceptions of whether a cultural object or genre is generally regarded as worthy) are distinguished from preferences (personal likes and dislikes) and both from the active consumption of specific cultural forms.</p>
<p>The key to the argument is that complex tastes emerge because these dimensions can come apart: individuals can like cultural forms they do not deem worthy, consume items they do not explicitly like, and regard as worthy genres they do not actively consume. Much like the distinction between stated and revealed preferences, individuals may overstate their consumption of higher-status cultural forms. Likewise, just as individuals provide justifications for lowbrow consumption—framing it as an “ironic” indulgence or a “guilty pleasure” <span class="citation" data-cites="mccoy2014guilty">(<a href="#ref-mccoy2014guilty" role="doc-biblioref">McCoy and Scarborough 2014</a>)</span>—in complex tastes they may overclaim or underclaim what they like relative to what they actually consume.</p>
<p>A pure self-report survey methodology is prone to underestimating complex tastes because of consistency bias <span class="citation" data-cites="podsakoff2003common">(<a href="#ref-podsakoff2003common" role="doc-biblioref">Podsakoff et al. 2003</a>)</span>, which arises when respondents seek to maintain logical or attitudinal consistency across questions by over-inflating claimed consumption to match their stated preferences. In this study, we examine overclaiming in cultural consumption within musical taste by contrasting abstract genre evaluations against playlist data. Overclaiming occurs when individuals report an affinity for a musical genre in the abstract, yet that genre is absent from the artists and tracks present in their verified listening repertoires. Abstract survey questions regarding cultural preferences may capture aspirational identities, symbolic boundary claiming, or socially desirable affiliations rather than routine everyday consumption. By contrasting abstract genre ratings with playlist data, this analysis evaluates the social distribution and structural determinants of symbolic cultural claims.</p>
<p>To investigate this phenomenon, we harmonize survey responses mapping abstract genre evaluations to verified playlist consumption across twenty musical genres. We estimate Bayesian crossed random-effects multinomial logistic regression models <span class="citation" data-cites="burkner2017brms">(<a href="#ref-burkner2017brms" role="doc-biblioref">Bürkner 2017</a>)</span> that simultaneously account for clustering across respondents and variation across musical genres. This modeling strategy permits genre-specific random slopes for cultural socialization, allowing us to test how early cultural capital shapes distinct complex tastes across varying positions in the cultural hierarchy.</p>
</section>
<section id="data-wrangling-variables-and-preparation" class="level1">
<h1>Data Wrangling, Variables, and Preparation</h1>
<p>The data preparation aligns self-reported recent listening streams with twenty standardized numeric genre codes and matches them with twenty corresponding survey items gauging abstract genre liking. The resulting dataset combines behavioral measures of consumption, abstract evaluative ratings, and demographic indicators.</p>
<section id="abstract-genre-liking" class="level3">
<h3 class="anchored" data-anchor-id="abstract-genre-liking">Abstract Genre Liking</h3>
<p>Abstract genre liking was assessed through the survey item: <em>“How much do you like listening to the following genres of music?”</em> Respondents evaluated their affinity for twenty musical genres (including Classical, Jazz, Musicals/Showtunes, Opera, and Rap/Hip-hop) on a seven-point Likert scale ranging from 1 (“Very Much Dislike”) to 7 (“Very Much Like”). This represents the standard approach to measuring cultural taste in social surveys <span class="citation" data-cites="bryson1996anything lizardo2016musical childress2021genres">(<a href="#ref-bryson1996anything" role="doc-biblioref">Bryson 1996</a>; <a href="#ref-lizardo2016musical" role="doc-biblioref">Lizardo and Skiles 2016</a>; <a href="#ref-childress2021genres" role="doc-biblioref">Childress et al. 2021</a>)</span>.</p>
</section>
<section id="concrete-listening-behavior" class="level3">
<h3 class="anchored" data-anchor-id="concrete-listening-behavior">Concrete Listening Behavior</h3>
<p>Concrete listening behavior was captured through a dedicated media player retrieval module. Respondents were first screened for their primary music listening platform (<code>how_listen</code>) and prompted regarding real-time access to their music libraries: <em>“Do you currently have access to your iTunes?”</em> (or Spotify / Winamp). For respondents with active player access, the survey provided specific instructions to open their media player application, sort their music library by “Plays” or play counts, and record the names of their top ten artists or bands alongside their associated play counts and genre tags (<code>itunes_1_1</code> through <code>itunes_10_3</code>, <code>spotify_comp1_1_1</code> through <code>spotify_phone1_10_1</code>, and <code>winamp_monkey_1_1</code> through <code>winamp_monkey_10_3</code>). For respondents accessing music without play count logging or through general streaming, the survey asked them to enter the top ten musical artists currently in regular rotation in their everyday listening (<code>rotation1_1_1</code> to <code>_rotation2_10</code>). The listed artists were subsequently classified into the corresponding twenty broad genre categories.</p>
</section>
<section id="complex-taste-indicators" class="level3">
<h3 class="anchored" data-anchor-id="complex-taste-indicators">Complex Taste Indicators</h3>
<p>We construct two binary indicators for each person-genre observation. Liking (<code>like</code>) is assigned a value of 1 if the respondent evaluated their affinity for the genre at 5, 6, or 7 on the seven-point scale, and 0 otherwise. Listening (<code>listen</code>) is assigned a value of 1 if the genre appeared at least once among the respondent’s top ten reported playlist artists, and 0 otherwise. The wide survey records are subsequently reshaped into a long-format structure in which the unit of analysis is the person-genre dyad.</p>
<p>To evaluate overclaiming within a unified categorical framework, we specify four mutually exclusive complex tastes for every person-genre dyad. The baseline complex taste, <em>Neither</em>, comprises instances where an individual neither likes nor listens to the genre. The <em>Underclaiming</em> (Listen Only) complex taste describes cases where an individual listens to an artist in that genre but does not express abstract liking, capturing unacknowledged or ambient consumption <span class="citation" data-cites="ma2026">(<a href="#ref-ma2026" role="doc-biblioref">Ma 2026</a>)</span>. The <em>Overclaiming</em> (Like Only) complex taste denotes instances where an individual expresses abstract liking for a genre that is absent from their listening repertoire, indicating symbolic claim without behavioral enactment. Finally, the <em>Consistent</em> (Both) complex taste captures congruent active engagement, where reported liking is accompanied by documented listening.</p>
</section>
<section id="cultural-capital-indicators" class="level3">
<h3 class="anchored" data-anchor-id="cultural-capital-indicators">Cultural Capital Indicators</h3>
<p>Early cultural socialization is measured by childhood arts exposure (<code>child_arts</code>), based on the survey item: <em>“During your childhood how frequently did your parents or guardians engage you with the arts?”</em>, rated on a seven-point scale from 1 (“Not At All”) to 7 (“All The Time”). Educational attainment (<code>educ2</code>) is derived from the survey prompt: <em>“What is the highest degree or level of school you have completed?”</em> The original seven response tiers (ranging from less than 9th grade to an advanced degree) are recoded into six analytical categories: Less than High School, High School Graduate, Some College, Associate’s Degree, Bachelor’s Degree, and Graduate Degree. Parental education (<code>parent_educ</code>) is constructed as the household maximum of maternal (<code>mom_educ</code>) and paternal (<code>dad_educ</code>) educational attainment using the identical six-tier scale.</p>
</section>
<section id="other-socio-demographic-variables" class="level3">
<h3 class="anchored" data-anchor-id="other-socio-demographic-variables">Other Socio-Demographic Variables</h3>
<p>Respondent demographic controls incorporate age, gender, household income, and ethnoracial background. Respondent age is elicited via birth year (ranging from 1928 to 2000) and categorized into six generational cohorts (<code>agecat</code>): Under 30 (born 1989–2000), 30–39 (born 1979–1988), 40–49 (born 1969–1978), 50–59 (born 1959–1968), 60–69 (born 1949–1958), and 70 and Older (born 1928–1948), entered in each model as a single ordinal variable. Gender is asked with options for Female, Male, and Other, operationalized in the regression equations as a binary indicator for women (<code>female</code>). Household income (<code>income</code>) is prompted through the question: <em>“Please indicate the answer that includes your entire household income before taxes”</em>, measured across twelve income brackets spanning from Less than $10,000, $10,000–$19,999, $20,000–$29,999, through subsequent $10,000 increments up to $150,000 or More. Ethnoracial identification (<code>race5</code>) collapses eight raw survey options (White, Black or African American, Native American, Pacific Islander, Hispanic/Latino, Asian, Middle Eastern, and Other) into five standardized categories: White (baseline), Black, Hispanic, Asian, and Other/Mixed. Finally, we adjust for streaming platform source (<code>platform</code>), which is classified into four operational modes: Free Recall, iTunes, Spotify, and Winamp.</p>
</section>
<section id="statistical-modeling-strategy" class="level3">
<h3 class="anchored" data-anchor-id="statistical-modeling-strategy">Statistical Modeling Strategy</h3>
<p>All data processing, Bayesian estimation, statistical analyses, and data visualizations are implemented in the R statistical computing environment (version 4.5.3; <span class="citation" data-cites="rcoreteam2026">R Core Team (<a href="#ref-rcoreteam2026" role="doc-biblioref">2026</a>)</span>). To accommodate the crossed hierarchical structure of the data (<span class="math inline">\(N = 1,574\)</span> respondents evaluated across <span class="math inline">\(J = 20\)</span> musical genres, yielding <span class="math inline">\(24,457\)</span> dyads), we estimate Bayesian crossed random-effects multinomial logistic regressions using the <code>brms</code> package (version 2.23.0; <span class="citation" data-cites="burkner2017brms">Bürkner (<a href="#ref-burkner2017brms" role="doc-biblioref">2017</a>)</span>; <span class="citation" data-cites="burkner2018advanced">Bürkner (<a href="#ref-burkner2018advanced" role="doc-biblioref">2018</a>)</span>) via the <code>cmdstanr</code> interface <span class="citation" data-cites="gabry2024cmdstanr">(<a href="#ref-gabry2024cmdstanr" role="doc-biblioref">Gabry et al. 2024</a>)</span> to CmdStan (version 2.39.0; <span class="citation" data-cites="stan2024cmdstan">Stan Development Team (<a href="#ref-stan2024cmdstan" role="doc-biblioref">2024</a>)</span>; <span class="citation" data-cites="carpenter2017stan">Carpenter et al. (<a href="#ref-carpenter2017stan" role="doc-biblioref">2017</a>)</span>).</p>
<p>Our analytical strategy proceeds in four sequential steps:</p>
<p>First, we estimate a baseline crossed random intercepts model with fixed effects for cultural capital and demographic covariates, examining overall genre-level tendencies to be overclaimed, underclaimed, or consistently engaged after correcting for baseline popularity.</p>
<p>Second, we implement a Bayesian formulation of the Wald test to evaluate the omnibus explanatory power of fixed-effects constructs, identify the primary cultural capital predictor, and inspect equation-specific parameter estimates across complex taste configurations alongside population-level predicted probabilities.</p>
<p>Third, we examine whether the returns to cultural capital vary across musical genres by evaluating random slopes models with progressively relaxed constraints.</p>
<p>Fourth, we analyze the structure of the genre random effects from the optimal specification to test whether high-cultural-capital individuals overclaim specific types of genres, evaluating how overclaiming odds relate to baseline popularity and educational class prestige.</p>
<p>In the baseline crossed random intercepts specification (Model 1), the linear predictor for respondent <span class="math inline">\(i\)</span> evaluating genre <span class="math inline">\(j\)</span> across active complex tastes <span class="math inline">\(s \in \{\text{ListenOnly}, \text{LikeOnly}, \text{Both}\}\)</span> relative to the baseline reference state <span class="math inline">\(\text{Neither}\)</span> is formulated as: <span class="math display">\[\eta_{ijs} = \alpha_s + \mathbf{X}_i \boldsymbol{\beta}_s + u_{0is} + u_{0js} \tag{1}\]</span> where <span class="math inline">\(\alpha_s\)</span> represents the state-specific intercept, <span class="math inline">\(\mathbf{X}_i\)</span> is the vector of respondent-level predictors with corresponding fixed-effect coefficient vector <span class="math inline">\(\boldsymbol{\beta}_s\)</span>, <span class="math inline">\(u_{0is} \sim \mathcal{N}(0, \sigma^2_{\text{id}, s})\)</span> represents the respondent random intercept capturing individual-level engagement propensities, and <span class="math inline">\(u_{0js} \sim \mathcal{N}(0, \sigma^2_{\text{genre}, s})\)</span> denotes the genre random intercept capturing baseline genre popularity. In this baseline specification, the effects of all individual-level predictors—including childhood arts exposure—are assumed to be homogeneous across genres.</p>
<p>To test whether the returns to cultural capital vary systematically across cultural genres, we extend the baseline model to the crossed random coefficients (random slopes) specification: <span class="math display">\[\eta_{ijs} = \alpha_s + \mathbf{X}_i \boldsymbol{\beta}_s + u_{0is} + u_{0js} + u_{1js} \cdot \text{child\_arts}_i \tag{2}\]</span> where <span class="math inline">\(u_{1js} \sim \mathcal{N}(0, \sigma^2_{\text{arts}, s})\)</span> is the genre-specific random slope allowing the effect of childhood arts exposure on state <span class="math inline">\(s\)</span> to vary across musical genres. Weakly informative regularizing priors are assigned to all fixed effects (<span class="math inline">\(\beta \sim \mathcal{N}(0, 1.5)\)</span>), random-effects standard deviations (<span class="math inline">\(\sigma \sim \text{Exponential}(1)\)</span>), and random-effects correlation matrices (<span class="math inline">\(\mathbf{\Omega} \sim \text{LKJ}(2)\)</span>). All models are estimated using Hamiltonian Monte Carlo across four chains with 2,000 iterations each (1,000 warmup iterations and 1,000 post-warmup sampling iterations per chain).</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="step-1-genre-level-complex-tastes-random-intercept-estimates" class="level2">
<h2 class="anchored" data-anchor-id="step-1-genre-level-complex-tastes-random-intercept-estimates">Step 1: Genre-Level Complex Tastes: Random Intercept Estimates</h2>
<p>To examine baseline propensities for each complex taste across the twenty musical genres after adjusting for individual-level demographics, we evaluate the genre random intercepts (<span class="math inline">\(u_{0j}\)</span>) from the baseline Bayesian crossed random intercepts model. In a multinomial logistic regression with reference baseline <span class="math inline">\(Y = \text{Neither}\)</span>, each of the three logit equations models the log-odds of entering state <span class="math inline">\(k \in \{\text{LikeOnly}, \text{ListenOnly}, \text{Both}\}\)</span> relative to complete non-engagement: <span class="math display">\[\log\left(\frac{P(Y = k \mid \text{genre } j)}{P(Y = \text{Neither} \mid \text{genre } j)}\right) = \alpha_k + u_{0j}^{(k)} + \mathbf{X}\boldsymbol{\beta}_k \tag{3}\]</span></p>
<p>Because all three logit equations share the identical baseline denominator (<span class="math inline">\(P(\text{Neither})\)</span>), the raw genre random intercepts <span class="math inline">\(u_{0j}^{(k)}\)</span> are heavily structured by overall genre popularity or the volume of complete population non-engagement. For niche or highbrow genres where the vast majority of respondents neither listen nor like (such as Opera at 80.2% <em>Neither</em> or Bluegrass at 63.0% <em>Neither</em>), the large baseline denominator shifts the random intercepts for all three complex tastes simultaneously into negative territory. Conversely, for widely popular mainstream genres (such as Classic Rock at 12.1% <em>Neither</em> and Contemporary Pop at 17.9% <em>Neither</em>), the small non-engagement baseline elevates intercepts across all three states into positive values.</p>
<p>Empirically, raw genre random intercepts across all three states correlate with overall genre popularity (<span class="math inline">\(P(\text{Any Engagement})\)</span>) at <span class="math inline">\(r &gt; 0.92\)</span>. Consequently, raw intercept rankings across states yield superficially similar hierarchies that primarily reflect genre mass appeal rather than distinct qualitative complex tastes. To isolate each genre’s qualitative tendency toward overclaiming, underclaiming, or consistent engagement, we correct for the shared popularity effect by calculating within-genre centered random intercepts across posterior draws: <span class="math display">\[\Delta u_{0j}^{(k)} = u_{0j}^{(k)} - \bar{u}_{0j}, \quad \text{where } \bar{u}_{0j} = \frac{1}{3}\sum_{m \in \{\text{LikeOnly}, \text{ListenOnly}, \text{Both}\}} u_{0j}^{(m)} \tag{5}\]</span></p>
<p>By subtracting the genre’s mean random intercept <span class="math inline">\(\bar{u}_{0j}\)</span>, the shared baseline volume cancels out. A positive deviation (<span class="math inline">\(\Delta u_{0j}^{(k)} &gt; 0\)</span>) signifies that a genre exhibits a disproportionate excess tilt toward complex taste <span class="math inline">\(k\)</span> relative to its own baseline engagement level, whereas <span class="math inline">\(\Delta u_{0j}^{(k)} &lt; 0\)</span> indicates under-representation in that complex taste. A deviation is classified as directional credible if at least 95% of its posterior probability density falls on one side of zero (<span class="math inline">\(\text{pd} \ge 0.95\)</span>). Figure 1 displays these popularity-purged engagement profiles across all twenty musical genres.</p>
<p><img src="Plots/Purged_Genre_Engagement_Profiles.png" class="img-fluid"></p>
<p>The popularity-corrected profiles suggest three distinct qualitative complex taste configurations across musical genres. In the symbolic overclaiming configuration, genres credibly tilted toward overclaiming (<em>Like Only</em>) include Bluegrass, Oldies, Musicals, Easy Listening, Jazz, Swing/Big Band, and Opera. Conditional on any engagement occurring, these styles are disproportionately liked in the abstract without corresponding playlist listening, which may reflect nostalgic affection (in the case of Oldies) or aspirational symbolic attachment (in the case of Opera, Jazz, and Musicals). In contrast, the consistent engagement configuration comprises genres credibly tilted toward <em>Both</em>, including Classic Rock, Country, Contemporary Rock, and Contemporary Pop. For these established genres, reported liking is corroborated by active listening repertoires. Finally, the underclaiming configuration includes styles credibly tilted toward <em>Listen Only</em>, such as Latin, Rap/Hip Hop, Heavy Metal, and Contemporary Pop. These genres exhibit elevated rates of playlist playback unaccompanied by reported high liking, likely reflecting ambient listening, algorithmic playlist exposure, or unacknowledged consumption.</p>
</section>
<section id="step-2-global-variable-importance-bayesian-joint-wald-tests" class="level2">
<h2 class="anchored" data-anchor-id="step-2-global-variable-importance-bayesian-joint-wald-tests">Step 2: Global Variable Importance: Bayesian Joint Wald Tests</h2>
<p>In multinomial logistic regression, categorical and continuous predictors contribute multiple parameters across competing logit equations. Evaluating individual coefficients in isolation can obscure the omnibus explanatory contribution of a construct across the full system of complex tastes. To establish an overall hierarchy of predictor importance, we test the joint null hypothesis that all parameters associated with a given construct are simultaneously zero (<span class="math inline">\(H_0: \boldsymbol{\beta}_k = \mathbf{0}\)</span>) across all three active complex taste logits relative to the baseline state (<em>Neither</em>).</p>
<p>We compute the Bayesian Joint Wald statistic using the posterior parameter distributions from the baseline crossed random intercepts model (Model 1). Estimating omnibus test statistics from this baseline model provides a clean assessment of global predictor importance before introducing genre-level slope variation. The test statistic is evaluated from the posterior mean parameter vector <span class="math inline">\(\bar{\boldsymbol{\beta}}_k = \mathbb{E}[\boldsymbol{\beta}_k \mid \mathcal{D}]\)</span> and the posterior covariance matrix <span class="math inline">\(\boldsymbol{\Sigma}_{\text{post}, k} = \text{Cov}_{\text{post}}(\boldsymbol{\beta}_k \mid \mathcal{D})\)</span>, calculated as the squared Mahalanobis distance from the null origin: <span class="math display">\[W_{\text{Bayes}} = \bar{\boldsymbol{\beta}}_k^\top \boldsymbol{\Sigma}_{\text{post}, k}^{-1} \bar{\boldsymbol{\beta}}_k \tag{4}\]</span></p>
<p>Under asymptotic posterior normality, <span class="math inline">\(W_{\text{Bayes}}\)</span> follows a <span class="math inline">\(\chi^2\)</span> distribution with degrees of freedom equal to the parameter count <span class="math inline">\(K = \dim(\boldsymbol{\beta}_k)\)</span>. Because the covariance matrix is derived directly from the hierarchical posterior draws, this test naturally incorporates uncertainty from both respondent- and genre-level clustering.</p>
<p><strong>Table 1: Joint Variable Importance (Bayesian Wald Chi-Square)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;">Chi_Square</th>
<th style="text-align: right;">DF</th>
<th style="text-align: left;">P_Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Childhood Arts Exposure</td>
<td style="text-align: right;">134.44</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">&lt; 0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Platform (Streaming Source)</td>
<td style="text-align: right;">40.10</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">&lt; 0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race / Ethnicity</td>
<td style="text-align: right;">18.48</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">0.102</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education</td>
<td style="text-align: right;">18.31</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">&lt; 0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age Category</td>
<td style="text-align: right;">9.24</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">0.026</td>
</tr>
<tr class="even">
<td style="text-align: left;">Parental Education</td>
<td style="text-align: right;">3.12</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">0.373</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Household Income</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">0.510</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender ID (Woman)</td>
<td style="text-align: right;">1.90</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">0.593</td>
</tr>
</tbody>
</table>
<section id="best-predictor-analysis" class="level3">
<h3 class="anchored" data-anchor-id="best-predictor-analysis">Best Predictor Analysis</h3>
<p>As Table 1 shows, the multivariate Wald tests identify childhood arts exposure as by far the primary predictor of complex musical tastes (<span class="math inline">\(\chi^2 = 134.44\)</span>, <span class="math inline">\(df = 3\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). Streaming platform retrieval method ranks second (<span class="math inline">\(\chi^2 = 40.10\)</span>, <span class="math inline">\(df = 9\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), reflecting differences in behavioral reporting precision across playlist platforms and recall modes. Ethnoracial identification (<span class="math inline">\(\chi^2 = 18.48\)</span>, <span class="math inline">\(df = 12\)</span>, <span class="math inline">\(p = 0.102\)</span>) and educational attainment (<span class="math inline">\(\chi^2 = 18.31\)</span>, <span class="math inline">\(df = 3\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) follow in explanatory magnitude. In contrast, parental education (<span class="math inline">\(\chi^2 = 3.12\)</span>, <span class="math inline">\(df = 3\)</span>, <span class="math inline">\(p = 0.373\)</span>), household income (<span class="math inline">\(\chi^2 = 2.31\)</span>, <span class="math inline">\(df = 3\)</span>, <span class="math inline">\(p = 0.510\)</span>), and gender identification (<span class="math inline">\(\chi^2 = 1.90\)</span>, <span class="math inline">\(df = 3\)</span>, <span class="math inline">\(p = 0.593\)</span>) display comparatively modest joint contributions, indicating that the transmission of parental social advantage into complex musical consumption is largely mediated through direct cultural socialization in childhood.</p>
</section>
<section id="detailed-coefficient-estimates-across-complex-tastes" class="level3">
<h3 class="anchored" data-anchor-id="detailed-coefficient-estimates-across-complex-tastes">Detailed Coefficient Estimates Across Complex Tastes</h3>
<p>The Bayesian parameter estimate tables present posterior distributions across all three active complex tastes relative to the baseline reference category (<em>Neither</em>). Posterior means and medians characterize central tendency, while the posterior standard deviation quantifies estimation uncertainty in a manner analogous to classical standard errors. The 95% Credible Intervals (2.5% to 97.5% quantiles) delineate the parameter range containing 95% of the posterior mass. The Probability of Direction (<span class="math inline">\(pd\)</span>) reports the proportion of posterior draws sharing the sign of the median estimate, indexing directional certainty where values exceeding 97.5% approximate conventional significance thresholds.</p>
<p><strong>Table 2: Predictors of Overclaiming (Like Only)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 22%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">Mean</th>
<th style="text-align: left;">Median</th>
<th style="text-align: left;">SD</th>
<th style="text-align: left;">CrI_2.5</th>
<th style="text-align: left;">CrI_97.5</th>
<th style="text-align: left;">pd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;"><b>-1.612***</b></td>
<td style="text-align: left;">-1.612</td>
<td style="text-align: left;">0.246</td>
<td style="text-align: left;">-2.096</td>
<td style="text-align: left;">-1.123</td>
<td style="text-align: left;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education</td>
<td style="text-align: left;"><b>0.070**</b></td>
<td style="text-align: left;">0.070</td>
<td style="text-align: left;">0.027</td>
<td style="text-align: left;">0.017</td>
<td style="text-align: left;">0.124</td>
<td style="text-align: left;">0.993</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parental Education</td>
<td style="text-align: left;">-0.026</td>
<td style="text-align: left;">-0.026</td>
<td style="text-align: left;">0.023</td>
<td style="text-align: left;">-0.071</td>
<td style="text-align: left;">0.019</td>
<td style="text-align: left;">0.867</td>
</tr>
<tr class="even">
<td style="text-align: left;">Childhood Arts Exposure</td>
<td style="text-align: left;"><b>0.231***</b></td>
<td style="text-align: left;">0.231</td>
<td style="text-align: left;">0.022</td>
<td style="text-align: left;">0.188</td>
<td style="text-align: left;">0.274</td>
<td style="text-align: left;">1.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age Category</td>
<td style="text-align: left;"><b>0.068**</b></td>
<td style="text-align: left;">0.068</td>
<td style="text-align: left;">0.023</td>
<td style="text-align: left;">0.022</td>
<td style="text-align: left;">0.112</td>
<td style="text-align: left;">0.996</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender ID (Woman)</td>
<td style="text-align: left;">0.030</td>
<td style="text-align: left;">0.030</td>
<td style="text-align: left;">0.069</td>
<td style="text-align: left;">-0.106</td>
<td style="text-align: left;">0.165</td>
<td style="text-align: left;">0.667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Household Income</td>
<td style="text-align: left;">-0.002</td>
<td style="text-align: left;">-0.001</td>
<td style="text-align: left;">0.011</td>
<td style="text-align: left;">-0.023</td>
<td style="text-align: left;">0.020</td>
<td style="text-align: left;">0.557</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race: Black</td>
<td style="text-align: left;"><b>0.259**</b></td>
<td style="text-align: left;">0.259</td>
<td style="text-align: left;">0.102</td>
<td style="text-align: left;">0.058</td>
<td style="text-align: left;">0.456</td>
<td style="text-align: left;">0.994</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race: Hispanic</td>
<td style="text-align: left;">0.019</td>
<td style="text-align: left;">0.018</td>
<td style="text-align: left;">0.103</td>
<td style="text-align: left;">-0.183</td>
<td style="text-align: left;">0.220</td>
<td style="text-align: left;">0.577</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race: Asian</td>
<td style="text-align: left;">0.280</td>
<td style="text-align: left;">0.284</td>
<td style="text-align: left;">0.160</td>
<td style="text-align: left;">-0.048</td>
<td style="text-align: left;">0.585</td>
<td style="text-align: left;">0.956</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race: Other/Mixed</td>
<td style="text-align: left;">0.097</td>
<td style="text-align: left;">0.097</td>
<td style="text-align: left;">0.170</td>
<td style="text-align: left;">-0.242</td>
<td style="text-align: left;">0.430</td>
<td style="text-align: left;">0.720</td>
</tr>
<tr class="even">
<td style="text-align: left;">Platform: Spotify</td>
<td style="text-align: left;">0.186</td>
<td style="text-align: left;">0.185</td>
<td style="text-align: left;">0.096</td>
<td style="text-align: left;">-0.001</td>
<td style="text-align: left;">0.373</td>
<td style="text-align: left;">0.975</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Platform: iTunes</td>
<td style="text-align: left;"><b>0.182*</b></td>
<td style="text-align: left;">0.184</td>
<td style="text-align: left;">0.088</td>
<td style="text-align: left;">0.006</td>
<td style="text-align: left;">0.355</td>
<td style="text-align: left;">0.980</td>
</tr>
<tr class="even">
<td style="text-align: left;">Platform: Winamp</td>
<td style="text-align: left;">0.604</td>
<td style="text-align: left;">0.612</td>
<td style="text-align: left;">0.480</td>
<td style="text-align: left;">-0.362</td>
<td style="text-align: left;">1.545</td>
<td style="text-align: left;">0.896</td>
</tr>
</tbody>
</table>
<p><strong>Table 3: Predictors of Underclaiming (Listen Only)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 22%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">Mean</th>
<th style="text-align: left;">Median</th>
<th style="text-align: left;">SD</th>
<th style="text-align: left;">CrI_2.5</th>
<th style="text-align: left;">CrI_97.5</th>
<th style="text-align: left;">pd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;"><b>-1.786***</b></td>
<td style="text-align: left;">-1.785</td>
<td style="text-align: left;">0.323</td>
<td style="text-align: left;">-2.424</td>
<td style="text-align: left;">-1.144</td>
<td style="text-align: left;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education</td>
<td style="text-align: left;"><b>0.092**</b></td>
<td style="text-align: left;">0.092</td>
<td style="text-align: left;">0.032</td>
<td style="text-align: left;">0.029</td>
<td style="text-align: left;">0.154</td>
<td style="text-align: left;">0.998</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parental Education</td>
<td style="text-align: left;">-0.028</td>
<td style="text-align: left;">-0.029</td>
<td style="text-align: left;">0.027</td>
<td style="text-align: left;">-0.081</td>
<td style="text-align: left;">0.022</td>
<td style="text-align: left;">0.855</td>
</tr>
<tr class="even">
<td style="text-align: left;">Childhood Arts Exposure</td>
<td style="text-align: left;">-0.014</td>
<td style="text-align: left;">-0.014</td>
<td style="text-align: left;">0.024</td>
<td style="text-align: left;">-0.062</td>
<td style="text-align: left;">0.033</td>
<td style="text-align: left;">0.716</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age Category</td>
<td style="text-align: left;">-0.002</td>
<td style="text-align: left;">-0.002</td>
<td style="text-align: left;">0.027</td>
<td style="text-align: left;">-0.055</td>
<td style="text-align: left;">0.050</td>
<td style="text-align: left;">0.528</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender ID (Woman)</td>
<td style="text-align: left;">0.003</td>
<td style="text-align: left;">0.003</td>
<td style="text-align: left;">0.081</td>
<td style="text-align: left;">-0.157</td>
<td style="text-align: left;">0.163</td>
<td style="text-align: left;">0.515</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Household Income</td>
<td style="text-align: left;">-0.015</td>
<td style="text-align: left;">-0.015</td>
<td style="text-align: left;">0.013</td>
<td style="text-align: left;">-0.041</td>
<td style="text-align: left;">0.010</td>
<td style="text-align: left;">0.875</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race: Black</td>
<td style="text-align: left;">0.076</td>
<td style="text-align: left;">0.077</td>
<td style="text-align: left;">0.121</td>
<td style="text-align: left;">-0.162</td>
<td style="text-align: left;">0.313</td>
<td style="text-align: left;">0.740</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race: Hispanic</td>
<td style="text-align: left;">0.224</td>
<td style="text-align: left;">0.220</td>
<td style="text-align: left;">0.120</td>
<td style="text-align: left;">-0.005</td>
<td style="text-align: left;">0.462</td>
<td style="text-align: left;">0.972</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race: Asian</td>
<td style="text-align: left;"><b>0.416*</b></td>
<td style="text-align: left;">0.421</td>
<td style="text-align: left;">0.188</td>
<td style="text-align: left;">0.049</td>
<td style="text-align: left;">0.776</td>
<td style="text-align: left;">0.988</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race: Other/Mixed</td>
<td style="text-align: left;">0.066</td>
<td style="text-align: left;">0.067</td>
<td style="text-align: left;">0.196</td>
<td style="text-align: left;">-0.313</td>
<td style="text-align: left;">0.453</td>
<td style="text-align: left;">0.632</td>
</tr>
<tr class="even">
<td style="text-align: left;">Platform: Spotify</td>
<td style="text-align: left;"><b>-0.375***</b></td>
<td style="text-align: left;">-0.376</td>
<td style="text-align: left;">0.113</td>
<td style="text-align: left;">-0.598</td>
<td style="text-align: left;">-0.155</td>
<td style="text-align: left;">1.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Platform: iTunes</td>
<td style="text-align: left;"><b>-0.489***</b></td>
<td style="text-align: left;">-0.490</td>
<td style="text-align: left;">0.106</td>
<td style="text-align: left;">-0.696</td>
<td style="text-align: left;">-0.281</td>
<td style="text-align: left;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Platform: Winamp</td>
<td style="text-align: left;">-0.298</td>
<td style="text-align: left;">-0.293</td>
<td style="text-align: left;">0.593</td>
<td style="text-align: left;">-1.508</td>
<td style="text-align: left;">0.827</td>
<td style="text-align: left;">0.689</td>
</tr>
</tbody>
</table>
<p><strong>Table 4: Predictors of Consistent Engagement (Both)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 22%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">Mean</th>
<th style="text-align: left;">Median</th>
<th style="text-align: left;">SD</th>
<th style="text-align: left;">CrI_2.5</th>
<th style="text-align: left;">CrI_97.5</th>
<th style="text-align: left;">pd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;"><b>-2.231***</b></td>
<td style="text-align: left;">-2.238</td>
<td style="text-align: left;">0.429</td>
<td style="text-align: left;">-3.065</td>
<td style="text-align: left;">-1.329</td>
<td style="text-align: left;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education</td>
<td style="text-align: left;"><b>0.091**</b></td>
<td style="text-align: left;">0.091</td>
<td style="text-align: left;">0.033</td>
<td style="text-align: left;">0.026</td>
<td style="text-align: left;">0.156</td>
<td style="text-align: left;">0.997</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parental Education</td>
<td style="text-align: left;">-0.035</td>
<td style="text-align: left;">-0.034</td>
<td style="text-align: left;">0.027</td>
<td style="text-align: left;">-0.090</td>
<td style="text-align: left;">0.019</td>
<td style="text-align: left;">0.896</td>
</tr>
<tr class="even">
<td style="text-align: left;">Childhood Arts Exposure</td>
<td style="text-align: left;"><b>0.141***</b></td>
<td style="text-align: left;">0.142</td>
<td style="text-align: left;">0.026</td>
<td style="text-align: left;">0.091</td>
<td style="text-align: left;">0.191</td>
<td style="text-align: left;">1.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age Category</td>
<td style="text-align: left;">-0.001</td>
<td style="text-align: left;">-0.001</td>
<td style="text-align: left;">0.026</td>
<td style="text-align: left;">-0.053</td>
<td style="text-align: left;">0.050</td>
<td style="text-align: left;">0.519</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender ID (Woman)</td>
<td style="text-align: left;">0.113</td>
<td style="text-align: left;">0.114</td>
<td style="text-align: left;">0.084</td>
<td style="text-align: left;">-0.054</td>
<td style="text-align: left;">0.280</td>
<td style="text-align: left;">0.910</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Household Income</td>
<td style="text-align: left;">0.011</td>
<td style="text-align: left;">0.011</td>
<td style="text-align: left;">0.013</td>
<td style="text-align: left;">-0.016</td>
<td style="text-align: left;">0.037</td>
<td style="text-align: left;">0.787</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race: Black</td>
<td style="text-align: left;">0.117</td>
<td style="text-align: left;">0.118</td>
<td style="text-align: left;">0.123</td>
<td style="text-align: left;">-0.126</td>
<td style="text-align: left;">0.353</td>
<td style="text-align: left;">0.830</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race: Hispanic</td>
<td style="text-align: left;">-0.099</td>
<td style="text-align: left;">-0.100</td>
<td style="text-align: left;">0.126</td>
<td style="text-align: left;">-0.346</td>
<td style="text-align: left;">0.156</td>
<td style="text-align: left;">0.785</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race: Asian</td>
<td style="text-align: left;">0.245</td>
<td style="text-align: left;">0.247</td>
<td style="text-align: left;">0.190</td>
<td style="text-align: left;">-0.132</td>
<td style="text-align: left;">0.612</td>
<td style="text-align: left;">0.902</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Race: Other/Mixed</td>
<td style="text-align: left;">-0.007</td>
<td style="text-align: left;">-0.004</td>
<td style="text-align: left;">0.206</td>
<td style="text-align: left;">-0.408</td>
<td style="text-align: left;">0.384</td>
<td style="text-align: left;">0.510</td>
</tr>
<tr class="even">
<td style="text-align: left;">Platform: Spotify</td>
<td style="text-align: left;">-0.098</td>
<td style="text-align: left;">-0.095</td>
<td style="text-align: left;">0.114</td>
<td style="text-align: left;">-0.332</td>
<td style="text-align: left;">0.115</td>
<td style="text-align: left;">0.806</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Platform: iTunes</td>
<td style="text-align: left;">-0.171</td>
<td style="text-align: left;">-0.171</td>
<td style="text-align: left;">0.105</td>
<td style="text-align: left;">-0.372</td>
<td style="text-align: left;">0.034</td>
<td style="text-align: left;">0.950</td>
</tr>
<tr class="even">
<td style="text-align: left;">Platform: Winamp</td>
<td style="text-align: left;">0.711</td>
<td style="text-align: left;">0.707</td>
<td style="text-align: left;">0.534</td>
<td style="text-align: left;">-0.350</td>
<td style="text-align: left;">1.738</td>
<td style="text-align: left;">0.908</td>
</tr>
</tbody>
</table>
<p>The posterior estimates from the baseline random intercepts model indicate that childhood arts exposure is a strong, substantively significant positive predictor of overclaiming (<span class="math inline">\(\bar{\beta} = 0.231\)</span>, 95% CrI: [0.188, 0.274], <span class="math inline">\(pd = 100\%\)</span>). While arts exposure also positively predicts consistent engagement (<span class="math inline">\(\bar{\beta} = 0.141\)</span>, 95% CrI: [0.091, 0.191], <span class="math inline">\(pd = 100\%\)</span>), its substantive effect on overclaiming is markedly larger. In contrast, childhood arts exposure does not reliably predict underclaiming (<span class="math inline">\(\bar{\beta} = -0.014\)</span>, 95% CrI: [-0.062, 0.033], <span class="math inline">\(pd = 71.6\%\)</span>). Educational attainment exhibits a consistent positive association across all three active complex tastes relative to non-engagement (<span class="math inline">\(\bar{\beta} = 0.070\)</span>, 95% CrI: [0.017, 0.124] for overclaiming; <span class="math inline">\(\bar{\beta} = 0.092\)</span>, 95% CrI: [0.029, 0.154] for underclaiming; and <span class="math inline">\(\bar{\beta} = 0.091\)</span>, 95% CrI: [0.026, 0.156] for consistent engagement), suggesting that the primary effect of acquired educational credentials is to move respondents out of complete non-engagement and into active engagement categories. In contrast, the credible intervals for parental education and household income include zero across all equations, demonstrating that the intergenerational transmission of socioeconomic advantage into complex musical consumption is largely mediated through direct cultural socialization rather than financial capital.</p>
</section>
<section id="visualizing-the-effect-of-arts-exposure-on-complex-tastes" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-the-effect-of-arts-exposure-on-complex-tastes">Visualizing the Effect of Arts Exposure on Complex Tastes</h3>
<p>To illustrate the substantive consequences of cultural capital across the complex taste typology, we compute posterior expected probabilities across the seven levels of childhood arts exposure from the baseline crossed random intercepts model, holding demographic covariates constant at sample medians and reference modes. Specifically, counterfactual expectations are generated across all 4,000 post-warmup Hamiltonian Monte Carlo posterior parameter draws for an idealized reference respondent with median education (tier 3, Some College), median parental education (tier 3), age cohort 30–39, male gender identification, median income bracket ($40,000–$49,999), White racial identification, and Free Recall platform reporting. Applying the multinomial softmax inverse-link transformation while integrating over the crossed random effects yields the full posterior predictive distribution of state probabilities <span class="math inline">\(\hat{P}(Y = k \mid \text{child\_arts})\)</span> for each exposure level.</p>
<p>The resulting posterior distributions are visualized using half-eye plots, which combine continuous density estimation with discrete interval summaries. For each level of arts exposure, the curved upper slab displays the posterior probability density function, visualizing the exact shape, spread, and skewness of the expected probability distribution. The solid central point denotes the posterior median (50th percentile), representing the primary estimate of central tendency, while the single horizontal error bar delineates the 95% credible interval (spanning the 2.5th and 97.5th percentiles). This integrated visual format allows for simultaneous inspection of central tendency, parametric uncertainty, and distributional asymmetries across the four complex tastes.</p>
<p><img src="Plots/ChildArts_Effects_Bayesian_CrI.png" class="img-fluid"></p>
<p>As Figure 2 illustrates, as childhood arts socialization shifts from minimal (<span class="math inline">\(1\)</span>) to extensive (<span class="math inline">\(7\)</span>), the predicted probability of overclaiming increases from 19.4% (95% CrI: [13.4%, 27.0%]) to 45.7% (95% CrI: [33.7%, 57.6%]), representing an increase of over 26 percentage points across the range of arts exposure. Over the same interval, the predicted probability of consistent engagement increases modestly from 9.0% (95% CrI: [4.4%, 18.7%]) to 12.5% (95% CrI: [6.0%, 25.3%]), while underclaiming declines from 11.1% to 6.0% and the probability of remaining unengaged (<em>Neither</em>) drops by more than half from 59.5% to 34.9%. Consequently, respondents with low exposure exhibit a markedly higher probability of complete non-engagement than overclaiming, whereas the reverse holds for respondents with extensive arts socialization. These divergent trajectories demonstrate that early cultural exposure exerts its primary substantive influence on expanding individuals’ propensity to trade non-engagement for symbolic overclaiming across unlistened genres.</p>
</section>
<section id="methodological-note-the-divergence-of-omnivorousness-and-cap-constraints" class="level3">
<h3 class="anchored" data-anchor-id="methodological-note-the-divergence-of-omnivorousness-and-cap-constraints">Methodological Note: The Divergence of Omnivorousness and Cap Constraints</h3>
<p>When respondents are allowed to rate 20 genres on a Likert scale but can only list up to 10 artists in regular rotation, it is reasonable to hypothesize whether a forced “ceiling effect” artifactually produces overclaiming among high-cultural-capital (CC) individuals. Specifically, if early socialization increases omnivorousness (the number of genres <em>liked</em>), high-CC respondents might simply run out of room in their top 10 artist slots, forcing them to mechanically overclaim on whatever genres didn’t make the cut.</p>
<p>However, the survey data refutes this mechanical constraint argument. As Figure 5 below illustrates, while childhood arts exposure sharply increases the volume of genres respondents <em>like</em> (from 5.7 genres at level 1, to 11.0 genres at level 7), their concrete behavioral listening footprint remains virtually flat (hovering between 3.4 and 3.8 genres on average).</p>
<p><img src="Plots/ChildArts_Omnivorousness_Capacity.png" class="img-fluid"></p>
<p>The median respondent only clusters their top 10 most-played artists into 3 distinct genres, and fewer than 1.1% of respondents list artists spanning exactly 10 distinct genres. High-CC respondents are not running out of room; they have ample “slack” to list artists from Opera or Classical music if they actively listened to them. Instead, they choose to allocate their 10 artists within the same few core popular genres (e.g., Rock or Pop) while leaving their highbrow, prestige tastes entirely in the abstract.</p>
<p>Furthermore, if the effect were purely a random mathematical artifact of the 10-artist cap, we would expect high-CC individuals to arbitrarily drop genres from their top 10 proportionally to baseline popularity. Instead, the Bayesian Crossed Random Slopes model confirms that the effect is highly structured and genre-specific: cultural capital drastically inflates overclaiming for high-prestige institutionalized genres (like Opera) while having no effect whatsoever on genres like Country (OR = 1.07). The “cap” is thus not a methodological flaw, but the exact mechanism that forces respondents to reveal which of their stated abstract tastes are deeply integrated into their active behavioral lives, and which serve as purely symbolic boundary markers.</p>
</section>
</section>
<section id="step-3-bayesian-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="step-3-bayesian-model-comparison">Step 3: Bayesian Model Comparison</h2>
<p>Having established that early arts exposure is the primary cultural capital predictor of complex tastes and is disproportionately tilted toward overclaiming, we next determine the optimal hierarchical structure for modeling multinomial taste engagement across respondents (<span class="math inline">\(N = 1,574\)</span>) and genres (<span class="math inline">\(J = 20\)</span>) when the returns to cultural capital are permitted to vary across musical genres. To do so, we evaluate five competing crossed mixed-effects specifications.</p>
<p>The baseline specification, Model 1 (Crossed Random Intercepts), incorporates respondent random intercepts <span class="math inline">\((1 \mid \text{id})\)</span> and genre random intercepts <span class="math inline">\((1 \mid \text{genre\_id})\)</span> across all three non-baseline logit equations, assuming that the effect of childhood arts exposure is uniform across genres. Model 2 (Constrained Random Slopes — Like Only) tests whether genre-level heterogeneity in arts socialization is restricted strictly to symbolic overclaiming by specifying random slopes <span class="math inline">\((1 + \text{child\_arts} \mid \text{genre\_id})\)</span> exclusively on the <code>LikeOnly</code> logit while maintaining random intercepts for <code>ListenOnly</code> and <code>Both</code>. Model 3 (Constrained Random Slopes — Under- and Overclaiming) permits genre-specific random slopes on both inconsistent complex tastes (<code>ListenOnly</code> and <code>LikeOnly</code>) while constraining <code>Both</code> to random intercepts. Model 4 (Constrained Random Slopes — Overclaiming &amp; Consistent Engagement) estimates genre-specific random slopes on both <code>LikeOnly</code> and <code>Both</code> while constraining <code>ListenOnly</code> to random intercepts. Finally, Model 5 (Full Crossed Random Slopes) freely estimates genre-level random slopes for childhood arts exposure alongside respondent-level random intercepts across all three logit equations.</p>
<p>We compare these specifications using the Widely Applicable Information Criterion (WAIC) and expected log predictive density (<span class="math inline">\(\text{elpd}_{\text{waic}}\)</span>). To facilitate interpretation, the comparison table breaks down the random-effects structure by explicitly indicating which of the three active complex taste equations—<em>Underclaiming</em> (Listen Only), <em>Overclaiming</em> (Like Only), or <em>Consistent Engagement</em> (Both)—incorporate genre-specific random slopes for childhood arts exposure (<span class="math inline">\(\checkmark\)</span>), with <em>Neither</em> serving as the baseline state. The <em>Parameters</em> column reports the total dimensionality of the estimated model, encompassing fixed regression coefficients, random-effect variance components, covariance parameters, and individual person- and genre-level random deviations. The expected log predictive density (<span class="math inline">\(\text{elpd}_{\text{waic}}\)</span>) and its accompanying standard error estimate how accurately the fitted model predicts new, unseen observations on the log-probability scale, where higher (less negative) values reflect superior predictive ability. The Widely Applicable Information Criterion (<span class="math inline">\(\text{WAIC}\)</span>) converts this predictive accuracy to the conventional deviance scale (<span class="math inline">\(\text{WAIC} = -2 \times \text{elpd}_{\text{waic}}\)</span>) while adjusting for effective model complexity, meaning that lower values denote a more favorable trade-off between fit and parsimony. Finally, <span class="math inline">\(\Delta\text{WAIC}\)</span> reports the relative difference in predictive error compared against the baseline random intercepts specification, where negative values indicate an improvement in out-of-sample performance.</p>
<p><strong>Table 5: Bayesian Mixed-Effects Model Fit Comparison</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 48%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 19%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Under</th>
<th style="text-align: left;">Over</th>
<th style="text-align: left;">Both</th>
<th style="text-align: left;">Par</th>
<th style="text-align: left;">WAIC (SE)</th>
<th style="text-align: left;">Delta_WAIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. Crossed Random Intercepts (Baseline)</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">4,820</td>
<td style="text-align: left;">48,917.4<br>(230.4)</td>
<td style="text-align: left;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. Constrained Slopes (Like Only)</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">4,840</td>
<td style="text-align: left;">48,823.9<br>(229.6)</td>
<td style="text-align: left;">-93.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. Constrained Slopes (Under- &amp; Overclaiming)</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">4,860</td>
<td style="text-align: left;">48,822.1<br>(229.5)</td>
<td style="text-align: left;">-95.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">4. Constrained Slopes (Overclaiming &amp; Consistent)</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">4,860</td>
<td style="text-align: left;">48,735.1<br>(229.5)</td>
<td style="text-align: left;">-182.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5. Full Crossed Random Slopes (Preferred)</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">4,880</td>
<td style="text-align: left;">48,732.4<br>(228.6)</td>
<td style="text-align: left;">-185.0</td>
</tr>
</tbody>
</table>
<p>The model comparison metrics demonstrate clear predictive gains as random slopes for cultural socialization are introduced and partitioned across complex tastes. Moving from the random intercepts baseline (Model 1) to Model 2, which allows random slopes strictly for overclaiming (<code>LikeOnly</code>), reduces WAIC by 93.5 points (<span class="math inline">\(\text{WAIC} = 48,823.9\)</span>). This substantial initial improvement confirms that early cultural capital induces overclaiming in ways that are not uniform across genres, but instead vary systematically according to the symbolic prestige of each musical style. Adding random slopes for underclaiming (<code>ListenOnly</code>) in Model 3 yields only a negligible incremental gain (<span class="math inline">\(\text{WAIC} = 48,822.1\)</span>, <span class="math inline">\(\Delta\text{WAIC} = -1.8\)</span> vs.&nbsp;Model 2), indicating that genre-level heterogeneity in cultural capital slopes is essentially absent for unacknowledged or ambient listening.</p>
<p>In contrast, Model 4—which specifies random slopes simultaneously on overclaiming (<code>LikeOnly</code>) and consistent consumption (<code>Both</code>) while constraining underclaiming (<code>ListenOnly</code>) to random intercepts—produces a dramatic leap in predictive accuracy (<span class="math inline">\(\text{WAIC} = 48,735.1\)</span>, <span class="math inline">\(\Delta\text{WAIC} = -182.3\)</span> relative to baseline, and <span class="math inline">\(\Delta\text{WAIC} = -88.8\)</span> relative to Model 2). This confirms that childhood arts socialization structures not only symbolic claiming but also consistent behavioral enactment across distinct musical styles. Finally, the fully unrestricted specification (Model 5) achieves the lowest overall deviance (<span class="math inline">\(\text{WAIC} = 48,732.4\)</span>, <span class="math inline">\(\Delta\text{WAIC} = -185.0\)</span> relative to Model 1), adding an incremental 2.7 WAIC points of predictive gain beyond Model 4. The comparison across these nested specifications demonstrates that early cultural capital operates decisively along two complex taste dimensions—Overclaiming (<code>LikeOnly</code>) and Consistent (<code>Both</code>)—while playing a negligible role in differentiating Underclaiming (<code>ListenOnly</code>) across genres. Because Model 5 provides the most comprehensive theoretical specification and optimal out-of-sample predictive performance, it serves as the primary basis for subsequent inferential tests.</p>
</section>
<section id="step-4-link-between-overclaiming-odds-and-genre-characteristics" class="level2">
<h2 class="anchored" data-anchor-id="step-4-link-between-overclaiming-odds-and-genre-characteristics">Step 4: Link Between Overclaiming Odds and Genre Characteristics</h2>
<section id="bayesian-posterior-odds-of-overclaiming" class="level3">
<h3 class="anchored" data-anchor-id="bayesian-posterior-odds-of-overclaiming">Bayesian Posterior Odds of Overclaiming</h3>
<p>For each genre <span class="math inline">\(j\)</span>, the total genre-specific effect of childhood arts exposure on the log-odds of overclaiming relative to non-engagement is defined as <span class="math inline">\(\beta_{\text{LikeOnly}, j} = \bar{\beta}_{\text{LikeOnly}} + u_{1j, \text{LikeOnly}}\)</span>. We evaluate the multiplicative change in the odds of overclaiming across the full range of arts exposure (<span class="math inline">\(\Delta = 6\)</span>) as <span class="math inline">\(\text{OR}_j = \exp(6 \cdot \beta_{\text{LikeOnly}, j})\)</span>. The posterior distributions are displayed below using half-eye visualizations depicting posterior medians alongside 95% credible intervals.</p>
<p><img src="Plots/ChildArts_Odds_Overclaiming_HalfEye.png" class="img-fluid"></p>
<p>The genre-specific distributions indicate marked stratification in responsiveness to cultural socialization. In Figure 3, genres are categorized into three levels based on the Educational Preference Ratio (the proportion of respondents with a Bachelor’s degree or higher who like the genre divided by the corresponding proportion among respondents with a High School education or less). The three categories are: preferred genres favored disproportionately by college graduates (ratio <span class="math inline">\(&gt; 1.25\)</span>, including Opera, Classical, Folk, Swing/Big Band, Musicals, Jazz, R&amp;B/Blues, and Bluegrass); slightly preferred genres with moderate educational affinity (ratio between <span class="math inline">\(1.0\)</span> and <span class="math inline">\(1.25\)</span>, including Reggae, Contemporary Pop, Latin, Easy Listening, Gospel, Contemporary Rock, and Oldies); and less preferred populist forms favored less by college graduates relative to high school graduates (ratio <span class="math inline">\(&lt; 1.0\)</span>, including Classic Rock, New Age, Country, Heavy Metal, and Rap/Hip Hop).</p>
<p>As Figure 3 shows, traditional highbrow genres exhibit the largest increases in overclaiming odds as childhood arts exposure increases, with Opera displaying a 15.2-fold increase (95% CrI: [8.46, 28.25]) and Classical music displaying a 12.0-fold increase (95% CrI: [7.07, 20.18]). Cosmopolitan genres such as Jazz (<span class="math inline">\(\text{OR} = 7.23\)</span>), Latin (<span class="math inline">\(\text{OR} = 7.08\)</span>), Swing/Big Band (<span class="math inline">\(\text{OR} = 6.78\)</span>), Reggae (<span class="math inline">\(\text{OR} = 6.19\)</span>), Musicals (<span class="math inline">\(\text{OR} = 5.68\)</span>), and New Age (<span class="math inline">\(\text{OR} = 5.36\)</span>) show five- to seven-fold increases. In contrast, commercial and populist genres exhibit comparatively subdued overclaiming propensities for high-cultural-capital individuals, with Country music representing the only genre whose 95% credible interval spans unity (<span class="math inline">\(\text{OR} = 1.07\)</span>, 95% CrI: [0.61, 1.82]).</p>
</section>
<section id="correlation-between-overclaiming-odds-and-genre-characteristics" class="level3">
<h3 class="anchored" data-anchor-id="correlation-between-overclaiming-odds-and-genre-characteristics">Correlation Between Overclaiming Odds and Genre Characteristics</h3>
<p>The negative link between genre baseline popularity and the tendency of high-cultural-capital respondents to overclaim them is apparent in Figure 4. In that figure, we assess the structural relationship between baseline genre popularity and responsiveness to overclaiming by early cultural socialization by comparing the uncorrected genre random intercepts (<span class="math inline">\(u_{0j}\)</span>) and random slopes (<span class="math inline">\(u_{1j}\)</span>) for the overclaiming equation.</p>
<p><img src="Plots/Overclaim_Random_Intercept_Slope_Correlation.png" class="img-fluid"></p>
<p>The genre random intercepts and slopes display a strong inverse correlation (<span class="math inline">\(r = -0.83\)</span>, Spearman <span class="math inline">\(\rho = -0.82\)</span>). This negative association demonstrates that culturally legitimated genres with low baseline popularity (such as Opera and Classical) exhibit the steepest increases in overclaiming in response to early arts socialization. Conversely, widely popular genres (such as Contemporary Pop or Classic Rock) show near-flat slopes, indicating that cultural capital is primarily mobilized when claiming affinity for comparatively exclusive or institutionalized cultural forms.</p>
<p><img src="Plots/Bayesian_Odds_Prestige_Correlation.png" class="img-fluid"></p>
<p>To directly evaluate whether overclaiming propensity tracks broader cultural legitimation boundaries, Figure 5 compares the genre-specific odds ratios against the Educational Preference Ratio. As shown, educational prestige correlates exceptionally strongly with the Bayesian odds ratios of overclaiming (<span class="math inline">\(r = 0.79\)</span>, Spearman <span class="math inline">\(\rho = 0.70\)</span>). Evaluating this association across all 4,000 posterior MCMC draws yields a median Pearson correlation of <span class="math inline">\(r = 0.74\)</span> (95% CrI: [0.60, 0.83]) and a median Spearman rank correlation of <span class="math inline">\(\rho = 0.65\)</span> (95% CrI: [0.51, 0.77]). By comparison, the correlation between overclaiming propensity and the racial preference ratio (Black-to-White liking ratio) is markedly weaker (<span class="math inline">\(\rho = 0.38\)</span>), demonstrating that symbolic overclaiming is structured primarily along educational and class-based legitimation boundaries rather than ethnoracial taste divisions.</p>
</section>
</section>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-bryson1996anything" class="csl-entry" role="listitem">
Bryson, Bethany. 1996. <span>“<span>‘<span>Anything</span> but Heavy Metal’</span>: Symbolic Exclusion and Musical Dislikes.”</span> <em>American Sociological Review</em> 61 (5): 884–99.
</div>
<div id="ref-burkner2017brms" class="csl-entry" role="listitem">
Bürkner, Paul-Christian. 2017. <span>“<span class="nocase">brms</span>: An <span>R</span> Package for <span>Bayesian</span> Multilevel Models Using <span>Stan</span>.”</span> <em>Journal of Statistical Software</em> 80 (1): 1–28. <a href="https://doi.org/10.18637/jss.v080.i01">https://doi.org/10.18637/jss.v080.i01</a>.
</div>
<div id="ref-burkner2018advanced" class="csl-entry" role="listitem">
Bürkner, Paul-Christian. 2018. <span>“Advanced <span>Bayesian</span> Multilevel Modeling with the <span>R</span> Package <span class="nocase">brms</span>.”</span> <em>The R Journal</em> 10 (1): 395–411. <a href="https://doi.org/10.32614/RJ-2018-017">https://doi.org/10.32614/RJ-2018-017</a>.
</div>
<div id="ref-carpenter2017stan" class="csl-entry" role="listitem">
Carpenter, Bob, Andrew Gelman, Matthew D. Hoffman, et al. 2017. <span>“Stan: A Probabilistic Programming Language.”</span> <em>Journal of Statistical Software</em> 76 (1): 1–32. <a href="https://doi.org/10.18637/jss.v076.i01">https://doi.org/10.18637/jss.v076.i01</a>.
</div>
<div id="ref-childress2021genres" class="csl-entry" role="listitem">
Childress, C. Clayton, Craig M. Rawlings, and Omar Lizardo. 2021. <span>“Genres and Fields: Measuring Symbolic Boundaries in Contemporary Music Consumption.”</span> <em>Poetics</em> 86: 101534.
</div>
<div id="ref-gabry2024cmdstanr" class="csl-entry" role="listitem">
Gabry, Jonah, Rok Češnovar, Andrew Johnson, and Steve Bronder. 2024. <em><span class="nocase">cmdstanr</span>: <span>R</span> Interface to <span>’CmdStan’</span></em>. <a href="https://mc-stan.org/cmdstanr/">https://mc-stan.org/cmdstanr/</a>.
</div>
<div id="ref-lizardo2016musical" class="csl-entry" role="listitem">
Lizardo, Omar, and Sara Skiles. 2016. <span>“Musical Taste and Social Class: How Cultural Capital Structures Everyday Listening.”</span> <em>Sociological Forum</em> 31 (2): 321–45.
</div>
<div id="ref-ma2025" class="csl-entry" role="listitem">
Ma, Long Do. 2025. <span>“Complex Tastes: Valuations, Preferences, and Consumption in Cultural Sociology.”</span> <em>Sociological Theory</em> 43 (2): 112–38.
</div>
<div id="ref-ma2026" class="csl-entry" role="listitem">
Ma, Long Do. 2026. <span>“Gender and Complex Tastes: Revisiting Cultural Stratification Beyond Simple Preferences.”</span> <em>Poetics</em> 108: 101850.
</div>
<div id="ref-mccoy2014guilty" class="csl-entry" role="listitem">
McCoy, Charles A., and Roscoe C. Scarborough. 2014. <span>“Guilty Pleasures: Cultural Distinction and the Justification of High and Low Taste.”</span> <em>Qualitative Sociology</em> 37 (1): 41–59.
</div>
<div id="ref-podsakoff2003common" class="csl-entry" role="listitem">
Podsakoff, Philip M., Scott B. MacKenzie, Jeong-Yeon Lee, and Nathan P. Podsakoff. 2003. <span>“Common Method Biases in Behavioral Research: A Critical Review of the Literature and Recommended Remedies.”</span> <em>Journal of Applied Psychology</em> 88 (5): 879–903.
</div>
<div id="ref-rcoreteam2026" class="csl-entry" role="listitem">
R Core Team. 2026. <em>R: A Language and Environment for Statistical Computing</em>. R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-stan2024cmdstan" class="csl-entry" role="listitem">
Stan Development Team. 2024. <em><span>CmdStan</span>: The Command-Line Interface to <span>Stan</span></em>. <a href="https://mc-stan.org/users/interfaces/cmdstan">https://mc-stan.org/users/interfaces/cmdstan</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>